# Generated by Django 3.2 on 2021-04-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMIS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
