# Generated by Django 3.2 on 2021-04-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMIS', '0004_auto_20210416_1950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treatmentplan',
            old_name='numAvailable',
            new_name='num',
        ),
        migrations.AddField(
            model_name='treatmentplan',
            name='numLimit',
            field=models.IntegerField(default=0),
        ),
    ]
