# Generated by Django 3.2 on 2021-04-17 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMIS', '0005_auto_20210417_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='num',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='numLimit',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.DeleteModel(
            name='TreatmentPlan',
        ),
    ]
