# Generated by Django 3.2 on 2021-04-17 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HMIS', '0007_auto_20210417_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentrecord',
            name='diagnosis',
            field=models.TextField(default='埋了吧', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='treatmentrecord',
            name='registration',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='HMIS.registrationrecord'),
            preserve_default=False,
        ),
    ]
